### ISSUE TITLE
@fetch-mock/vitest todo

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#812]
- [ ] README
- [ ] docs (API and usage guide)
- [ ] @fetch-mock/jest (maybe have some shared code for now?)
- [ ] tests and API design for hook into lifecycle
- [ ] Decision on whether to prefix methods with `mock` (perhaps they should live on @fetch-mock/core, but aliased with the `mock` prefix on the vitest package?)
- [ ] Metadata in package.json's e.g. author

**Comment by wheresrhys** [comment]
perhaps `mockReset()` etc should be added onto `fetchHandler`?

so `fetchMock.reset()`, but `fetch.mockReset()`?
